version: 2
jobs:
  noop:
    machine: true
    steps:
      - checkout

workflows:
  version: 2
  release:
    jobs:
      - noop:
          filters:
            tags:
              ignore: /.*/
            branches:
              ignore: /.*/